version: '3'

tasks:
  init:
    desc: "init this packages dev depends"
    cmds:
      - poetry update
      - poetry install
      - poetry lock

  lint:
    desc: "Lint this package"
    cmds:
      - ruff check --fix
      - pre-commit run --all-files --color always

  test:
    desc: "Test this package"
    cmds:
      - coverage run
      - coverage report
      - coverage xml

  docs_serve:
    desc: "open docs_ server"
    cmds:
      - poetry run mkdocs serve {{.CLI_ARGS}}

  deploy_pages:
    desc: "deploy new docs pages"
    cmds:
      - poetry install
      - poetry run mkdocs gh-deploy --remote-branch gh-pages --force

  build:
    desc: "Build the package"
    cmds:
      - poetry build

  publish_package:
    desc: "build test and publish packages"
    cmds:
      - task: init
      - task: lint
      - task: test
      - task: build
#      - poetry publish