name: CI
on:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7","3.8","3.9","3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup poetry
        uses: abatilo/actions-poetry@v2

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        run: task init

      - name: build
        run: task build

      - name: Configure TestPyPI
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Publish package to TestPyPI
        run: poetry publish -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Install package from TestPyPI
        run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple workflowtest

#      - name: Publish package to PyPI
#        run: poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
