name: deploy docs

on:
  workflow_run:
    workflows: [ bump_version ]
    types: [ completed ]
    branches: [ master ]

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install poetry
        uses: abatilo/actions-poetry@v2

      - run: task deploy_pages