name: publish site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # 创建一个 Ubuntu 容器
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip && python -m pip install -U pip poetry
      - run: poetry --version
      - run: task deploy_pages